# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingelement',
            name='rails',
        ),
        migrations.AddField(
            model_name='codingelement',
            name='username',
            field=models.CharField(default='GuestName', max_length=100),
        ),
    ]
