# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textCoder', '0002_auto_20200524_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingelement',
            name='rails',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingelement',
            name='textEncoded',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='codingelement',
            name='textEntered',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
